config/routes.rb
Rails.application.routes.draw do
  resources :tweeters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeter.rb
class Tweeter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweeters_controller.rb
class TweetersController < ApplicationController
  before_action :set_tweeter, only: [:show, :edit, :update, :destroy]

  # GET /tweeters
  # GET /tweeters.json
  def index
    @tweeters = Tweeter.all
  end

  # GET /tweeters/1
  # GET /tweeters/1.json
  def show
  end

  # GET /tweeters/new
  def new
    @tweeter = Tweeter.new
  end

  # GET /tweeters/1/edit
  def edit
  end

  # POST /tweeters
  # POST /tweeters.json
  def create
    @tweeter = Tweeter.new(tweeter_params)

    respond_to do |format|
      if @tweeter.save
        format.html { redirect_to @tweeter, notice: 'Tweeter was successfully created.' }
        format.json { render :show, status: :created, location: @tweeter }
      else
        format.html { render :new }
        format.json { render json: @tweeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeters/1
  # PATCH/PUT /tweeters/1.json
  def update
    respond_to do |format|
      if @tweeter.update(tweeter_params)
        format.html { redirect_to @tweeter, notice: 'Tweeter was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeter }
      else
        format.html { render :edit }
        format.json { render json: @tweeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeters/1
  # DELETE /tweeters/1.json
  def destroy
    @tweeter.destroy
    respond_to do |format|
      format.html { redirect_to tweeters_url, notice: 'Tweeter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeter
      @tweeter = Tweeter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweeter_params
      params.fetch(:tweeter, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeters_helper.rb
module TweetersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweeters/_form.html.erb
<%= form_with(model: tweeter, local: true) do |form| %>
  <% if tweeter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeter.errors.count, "error") %> prohibited this tweeter from being saved:</h2>

      <ul>
      <% tweeter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeters/edit.html.erb
<h1>Editing Tweeter</h1>

<%= render 'form', tweeter: @tweeter %>

<%= link_to 'Show', @tweeter %> |
<%= link_to 'Back', tweeters_path %>

app/views/tweeters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweeters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeters.each do |tweeter| %>
      <tr>
        <td><%= link_to 'Show', tweeter %></td>
        <td><%= link_to 'Edit', edit_tweeter_path(tweeter) %></td>
        <td><%= link_to 'Destroy', tweeter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweeter', new_tweeter_path %>

app/views/tweeters/new.html.erb
<h1>New Tweeter</h1>

<%= render 'form', tweeter: @tweeter %>

<%= link_to 'Back', tweeters_path %>

app/views/tweeters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweeter_path(@tweeter) %> |
<%= link_to 'Back', tweeters_path %>